In [ ]:
import tensorflow as tf
from aMNWtModel import AMNWtModel


seed = 10
# np.random.seed(seed=seed)  
# tf.random.set_seed(seed)


dataset_file = "./Dataset/biolog_iML1515_EXP_UB.npz"
objective=['BIOMASS_Ec_iML1515_core_75p37M']
epoch = 1
batch_size = 30


print("---------------------------------------- model ----------------------------------------")
model = AMNWtModel(dataset_file=dataset_file, 
                   objective=objective,
                   timestep=4,
                #    n_hidden=1, 
                   hidden_dim=50,
                   epochs=50, 
                   verbose=True,
                   batch_size=7)
model.printout()

# Preprocessing
from sklearn.preprocessing import MinMaxScaler,StandardScaler,MaxAbsScaler 
from tools import MaxScaler
scaler= MaxScaler()
model.train_test_split(test_size=0.1, random_state=seed)
model.preprocess(scaler)
model.preprocessing_for_specific_model()

---------------------------------------- model ----------------------------------------
number of metabolites:  1877
filtered measurements size:  1
dataset file: ./Dataset/biolog_iML1515_EXP_UB.npz
model type: AMNWt
model medium bound: UB
timestep: 4
training set size (17400, 430) (17400, 1)
training epochs: 50
training regression: True
training batch size: 7
training validation iter: 0
training early stopping: False

##Â This notebook manipulate the biolog dataset with KO

In [2]:
import pandas as pd 
df = pd.read_csv("Dataset_input/biolog_iML1515_EXP.csv",)

In [6]:
medium_col = df.columns[:151]
df_medium = df[medium_col]
df_medium.describe()

,EX_nh4_e_i,EX_pi_e_i,EX_co2_e_i,EX_fe3_e_i,EX_h_e_i,EX_mn2_e_i,EX_fe2_e_i,EX_zn2_e_i,EX_mg2_e_i,EX_ca2_e_i,...,EX_tym_e_i,EX_tyr__L_e_i,EX_tyrp_e_i,EX_ura_e_i,EX_urea_e_i,EX_uri_e_i,EX_val__L_e_i,EX_xan_e_i,EX_xtsn_e_i,EX_xyl__D_e_i
count,17400.0,17400.0,17400.0,17400.0,17400.0,17400.0,17400.0,17400.0,17400.0,17400.0,...,17400.000000,17400.000000,17400.000000,17400.000000,17400.000000,17400.000000,17400.000000,17400.000000,17400.000000,17400.000000
mean,10.0,10.0,50.0,10.0,50.0,10.0,10.0,10.0,10.0,10.0,...,0.068966,0.068966,0.068966,0.068966,0.068966,0.137931,0.137931,0.068966,0.068966,0.068966
std,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.827610,0.827610,0.827610,0.827610,0.827610,1.166346,1.166346,0.827610,0.827610,0.827610
min,10.0,10.0,50.0,10.0,50.0,10.0,10.0,10.0,10.0,10.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,10.0,10.0,50.0,10.0,50.0,10.0,10.0,10.0,10.0,10.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,10.0,10.0,50.0,10.0,50.0,10.0,10.0,10.0,10.0,10.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,10.0,10.0,50.0,10.0,50.0,10.0,10.0,10.0,10.0,10.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,10.0,10.0,50.0,10.0,50.0,10.0,10.0,10.0,10.0,10.0,...,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000

In [10]:
df_GR = df["GR_AVG"]

In [11]:
df_no_knock_out = pd.concat([df_medium, df_GR], axis=1)
df_knockout = df[df.columns[151:-1]]

In [42]:
df_no_knock_out.to_csv("./Dataset_input/biolog_iML1515_medium_and_GR.csv",index=False)
df_knockout.to_csv("./Dataset_input/biolog_iML1515_knockout.csv",index=False)

In [14]:
df_KO = df_knockout*100

In [16]:
df_new = df_no_knock_out = pd.concat([df_medium,df_KO, df_GR], axis=1)

In [18]:
df_new.to_csv("./Dataset_input/biolog_iML1515_new.csv",index=False)